export const navLinks = [
    {
        id:1,
        url:"#home",
        label:"Home"
    },
    {
        id:2,
        url:"#about",
        label:"About"
    },
    {
        id:3,
        url:"#journey",
        label:"Journey"
    },
    {
        id:4,
        url:"#services",
        label:"Services"
    },
    {
        id:5,
        url:"#skill",
        label:"Skill"
    },
    {
        id:6,
        url:"#my_project",
        label:"Projects"
    },
    {
        id:7,
        url:"#contact",
        label:"Contact"
    }
]